import { Geist, Geist_Mono, Noto_Sans_Lao } from "next/font/google";
import "./globals.css";
import { FirebaseProvider } from "../firebase/context";
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSansLao = Noto_Sans_Lao({
  variable: "--font-noto-sans-lao",
  subsets: ["lao"],
  weight: ['400', '700'], // Specify weights you need
  display: 'swap',
});

export const metadata = {
  title: "LSD Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="lo">
      <body
        className={`${notoSansLao.variable} ${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
      >
        <FirebaseProvider>
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 4000,
              style: {
                background: '#363636',
                color: '#fff',
                fontFamily: 'var(--font-noto-sans-lao), sans-serif',
              },
              success: {
                duration: 3000,
                style: {
                  background: '#00b09b',
                  color: '#fff',
                },
              },
              error: {
                duration: 5000,
                style: {
                  background: '#ff5252',
                  color: '#fff',
                },
              },
            }}
          />
        </FirebaseProvider>
      </body>
    </html>
  );
}
